local-phone-apps = AppInstaller \
                   ApplicationsProvider \
                   BackupRestoreConfirmation \
                   Bluetooth \
                   Browser \
                   CalendarProvider \
                   CertInstaller \
                   Contacts \
                   ContactsProvider \
                   DefaultContainerService \
                   DownloadProvider \
                   DownloadProviderUi \
                   DrmProvider \
                   EnjoyTV-Receiver \
                   Exchange2 \
                   Galaxy4 \
                   GoogleCalendarSyncAdapter \
                   GoogleLoginService \
                   GoogleServicesFramework \
                   HTMLViewer \
                   HoloSpiralWallpaper \
                   InputDevices \
                   KeyChain \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   MusicFX \
                   MusicPlayer \
                   NoiseField \
                   PPPoE \
                   PackageInstaller \
                   PhaseBeam \
                   Phone \
                   PicoTts \
                   PicturePlayer \
                   PreloadInstall \
                   Provision \
                   RemoteIME \
                   Samba \
                   Settings \
                   SettingsProvider \
                   SharedStorageBackup \
                   SoundRecorder \
                   SystemUI \
                   TelephonyProvider \
                   Upgrade \
                   UserDictionaryProvider \
                   Vending \
                   VideoPlayer \
                   VisualizationWallpapers \
                   VpnDialogs \
                   WAPPushManager \
                   com.mygica.launcher \
                   oem_install_flash_player_jb